#767: Adds improved state/lockfile handling.

diff --git a/src/usr/sbin/sshd-bootstrap b/src/usr/sbin/sshd-bootstrap
--- a/src/usr/sbin/sshd-bootstrap
+++ b/src/usr/sbin/sshd-bootstrap
@@ -1,288 +1,134 @@
 #!/usr/bin/env bash
 
-function __is_sudo_no_password_all ()
+set -e
+
+function __cleanup ()
 {
-	local -r sudo="${1}"
-	local -r pattern=' ?NOPASSWD:ALL$'
+	local -r exit_code="${?}"
 
-	if [[ ${sudo} =~ ${pattern} ]]
+	__delete_lock
+
+	if [[ ${exit_code} -eq 0 ]]
 	then
-		return 0
+		__create_state
 	fi
-
-	return 1
 }
 
-function __is_valid_ssh_authorized_keys ()
+function __create_lock ()
 {
-	local -r authorized_keys="${1}"
-	local -r invalid_key_pattern='is not a public key file.$'
-
-	local ssh_key
-	local IFS=""
-
-	if [[ -z ${authorized_keys} ]]
+	if [[ -n ${lock_file} ]]
 	then
+		touch "${lock_file}"
+	fi
+}
+
+function __create_state ()
+{
+	if [[ -n ${state_file} ]]
+	then
+		touch "${state_file}"
+	fi
+}
+
+function __delete_lock ()
+{
+	if [[ -e ${lock_file} ]]
+	then
+		rm -f "${lock_file}"
+	fi
+}
+
+function __generate_ssh_host_key ()
+{
+	local -r replace="${1:-false}"
+	local -r type="${2:-rsa}"
+
+	local private_key_path
+	local public_key_path
+	local response='n\n'
+
+	if [[ ${replace} == true ]]
+	then
+		response='y\n'
+	fi
+
+	case "${type}" in
+		rsa1|rsa|dsa|ecdsa|ed25519)
+			if [[ ${type} != rsa1 ]]
+			then
+				private_key_path=/etc/ssh/ssh_host_"${type}"_key
+				public_key_path=/etc/ssh/ssh_host_"${type}"_key.pub
+			else
+				private_key_path=/etc/ssh/ssh_host_key
+				public_key_path=/etc/ssh/ssh_host_key.pub
+			fi
+
+			printf -- \
+				"${response}" \
+			| ssh-keygen \
+				-q \
+				-C "" \
+				-N "" \
+				-t "${type}" \
+				-f "${private_key_path}" \
+				&> /dev/null
+
+			if [[ -x /sbin/restorecon ]]
+			then
+				/sbin/restorecon "${public_key_path}"
+			fi
+
+			;;
+		*)
+			printf -- \
+				'Unknown key type %s - skipping.\n' \
+				"${type}"
+			;;
+	esac
+}
+
+function __generate_ssh_host_keys ()
+{
+	local -r replace="${1:-false}"
+
+	local version="${2}"
+
+	if [[ -z ${version} ]] \
+		&& [[ -e /etc/redhat-release ]]
+	then
+		version="$(
+			rpm -q \
+				--whatprovides redhat-release \
+				--queryformat "%{VERSION}"
+		)"
+	else
+		printf -- \
+			'ERROR: Unknown EL release.\n' \
+			>&2
+		sleep 0.1
+
 		return 1
 	fi
 
-	while read -r ssh_key || [[ -n ${ssh_key} ]]
-	do
-		if [[ -n ${ssh_key} ]] \
-			&& [[ $(
-				__get_ssh_key_fingerprint "${ssh_key}"
-			) =~ ${invalid_key_pattern} ]]
-		then
-			return 1
-		fi
-	done <<< "${authorized_keys}"
-
-	return 0
-}
-
-function __is_valid_ssh_chroot_directory ()
-{
-	local -r chroot_directory="${1}"
-	local -r safe_directory='^(%h|\/(?!\/|bin|dev|etc|lib|lib64|lost+found|media|proc|root|sbin|srv|sys|tmp|usr).+)$'
-
-	if [[ -z ${chroot_directory} ]]
-	then
-		return 1
-	fi
-
-	if grep -qoP "${safe_directory}" <<< "${chroot_directory}"
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_inherit_environment ()
-{
-	local -r boolean_value='^(true|false)$'
-	local -r value="${1}"
-
-	if [[ ${value} =~ ${boolean_value} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_key ()
-{
-	local -r public_key="${1}"
-	local -r invalid_key_pattern='is not a public key file.$'
-
-	if [[ -z ${public_key} ]]
-	then
-		return 1
-	fi
-
-	if [[ -n ${public_key} ]] \
-		&& [[ $(
-			__get_ssh_key_fingerprint "${public_key}"
-		) =~ ${invalid_key_pattern} ]]
-	then
-		return 1
-	fi
-
-	return 0
-}
-
-function __is_valid_ssh_password_authentication ()
-{
-	local -r boolean_value='^(true|false)$'
-	local -r value="${1}"
-
-	if [[ ${value} =~ ${boolean_value} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_sudo ()
-{
-	local -r temp_path="$(
-		mktemp -u
-	)"
-	local -r sudo_cmd="${1}"
-
-	if [[ -z ${sudo_cmd} ]]
-	then
-		return 1
-	fi
-
-	trap \
-		"rm -f \"${temp_path}\"" \
-		EXIT INT RETURN TERM
-
-	printf -- \
-		'%%wheel %s\n' \
-		"${sudo_cmd}" \
-		> "${temp_path}"
-
-	if visudo \
-		-c \
-		-q \
-		-f "${temp_path}" \
-		&> /dev/null
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_timezone ()
-{
-	local -r zone="${1}"
-
-	if [[ -z ${zone} ]]
-	then
-		return 1
-	fi
-
-	if [[ -f /usr/share/zoneinfo/${zone} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_user ()
-{
-	local -r safe_user='^[a-z_][a-z0-9_-]{0,29}[$a-z0-9_]?$'
-	local -r user="${1}"
-
-	if [[ ${user} =~ ${safe_user} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_user_force_sftp ()
-{
-	local -r boolean_value='^(true|false)$'
-	local -r value="${1}"
-
-	if [[ ${value} =~ ${boolean_value} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_user_home ()
-{
-	local -r home_directory="${1}"
-	local -r user_directory='^\/(?!\/|bin|dev|etc|lib|lib64|lost+found|media|proc|root|sbin|srv|sys|tmp|usr).+$'
-	local -r root_directory='^/root$'
-	local -r user="${2:-"$(
-		__get_ssh_user
-	)"}"
-
-	local safe_directory="${user_directory}"
-
-	if [[ -z ${home_directory} ]]
-	then
-		return 1
-	fi
-
-	if [[ ${user} == root ]]
-	then
-		safe_directory="${root_directory}"
-	fi
-
-	if grep -qoP "${safe_directory}" <<< "${home_directory}"
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_user_id ()
-{
-	local -r id="${1}"
-	local -r user_id_pattern='^[1-9][0-9]*:[1-9][0-9]*$'
-	local -r root_id_pattern='^0:0$'
-	local -r user="${2:-"$(
-		__get_ssh_user
-	)"}"
-
-	local id_pattern="${user_id_pattern}"
-
-	if [[ ${user} == root ]]
-	then
-		id_pattern="${root_id_pattern}"
-	fi
-
-	if [[ ${id} =~ ${id_pattern} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_user_password_hash ()
-{
-	local -r password_hash="${1}"
-	local -r sha_512_pattern='^\$6\$[a-zA-Z0-9./]{0,16}\$[a-zA-Z0-9./]{86}$'
-
-	if [[ ${password_hash} =~ ${sha_512_pattern} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_user_password_hashed ()
-{
-	local -r boolean_value='^(true|false)$'
-	local -r value="${1}"
-
-	if [[ ${value} =~ ${boolean_value} ]]
-	then
-		return 0
-	fi
-
-	return 1
-}
-
-function __is_valid_ssh_user_shell ()
-{
-	local -r shell="${1}"
-	local -r valid_shells="$(
-		chsh --list-shells
-	)"
-
-	local valid_shell
-
-	if [[ -z ${shell} ]]
-	then
-		return 1
-	fi
-
-	for valid_shell in ${valid_shells}
-	do
-		if [[ ${valid_shell} == "${shell}" ]]
-		then
-			return 0
-		fi
-	done
-
-	return 1
+	case "${version}" in
+		6)
+			__generate_ssh_host_key "${replace}" rsa1
+			__generate_ssh_host_key "${replace}" rsa
+			__generate_ssh_host_key "${replace}" dsa
+			;;
+		7)
+			__generate_ssh_host_key "${replace}" rsa1
+			__generate_ssh_host_key "${replace}" rsa
+			__generate_ssh_host_key "${replace}" dsa
+			__generate_ssh_host_key "${replace}" ecdsa
+			__generate_ssh_host_key "${replace}" ed25519
+			;;
+		*)
+			printf -- \
+				'Unknown EL release %s - skipping.\n' \
+				"${version}"
+			;;
+	esac
 }
 
 function __get_password ()
@@ -746,97 +592,313 @@ function __get_ssh_user_uid ()
 	printf -- '%d' "${value}"
 }
 
-function __generate_ssh_host_key ()
+function __get_timer_total ()
 {
-	local -r replace="${1:-false}"
-	local -r type="${2:-rsa}"
+	local -r timer_end="$(
+		date +%s.%N
+	)"
+	local -r timer_start="${1}"
 
-	local private_key_path
-	local public_key_path
-	local response='n\n'
-
-	if [[ ${replace} == true ]]
+	if [[ -z ${timer_start} ]] \
+		|| [[ ${timer_start//.} -gt ${timer_end//.} ]]
 	then
-		response='y\n'
+		>&2 printf -- \
+			'ERROR: invalid timer start: %s\n' \
+			"${timer_start}"
+		printf -- \
+			'0.000000'
+	else
+		awk \
+			-v timer_end="${timer_end}" \
+			-v timer_start="${timer_start}" \
+			'BEGIN { print \
+				timer_end - timer_start;
+			}'
 	fi
-
-	case "${type}" in
-		rsa1|rsa|dsa|ecdsa|ed25519)
-			if [[ ${type} != rsa1 ]]
-			then
-				private_key_path=/etc/ssh/ssh_host_"${type}"_key
-				public_key_path=/etc/ssh/ssh_host_"${type}"_key.pub
-			else
-				private_key_path=/etc/ssh/ssh_host_key
-				public_key_path=/etc/ssh/ssh_host_key.pub
-			fi
-
-			printf -- \
-				"${response}" \
-			| ssh-keygen \
-				-q \
-				-C "" \
-				-N "" \
-				-t "${type}" \
-				-f "${private_key_path}" \
-				&> /dev/null
-
-			if [[ -x /sbin/restorecon ]]
-			then
-				/sbin/restorecon "${public_key_path}"
-			fi
-
-			;;
-		*)
-			printf -- \
-				'Unknown key type %s - skipping.\n' \
-				"${type}"
-			;;
-	esac
 }
 
-function __generate_ssh_host_keys ()
+function __is_sudo_no_password_all ()
 {
-	local -r replace="${1:-false}"
+	local -r sudo="${1}"
+	local -r pattern=' ?NOPASSWD:ALL$'
 
-	local version="${2}"
-
-	if [[ -z ${version} ]] \
-		&& [[ -e /etc/redhat-release ]]
+	if [[ ${sudo} =~ ${pattern} ]]
 	then
-		version="$(
-			rpm -q \
-				--whatprovides redhat-release \
-				--queryformat "%{VERSION}"
-		)"
-	else
-		printf -- \
-			'ERROR: Unknown EL release.\n' \
-			>&2
-		sleep 0.1
+		return 0
+	fi
 
+	return 1
+}
+
+function __is_valid_ssh_authorized_keys ()
+{
+	local -r authorized_keys="${1}"
+	local -r invalid_key_pattern='is not a public key file.$'
+
+	local ssh_key
+	local IFS=""
+
+	if [[ -z ${authorized_keys} ]]
+	then
 		return 1
 	fi
 
-	case "${version}" in
-		6)
-			__generate_ssh_host_key "${replace}" rsa1
-			__generate_ssh_host_key "${replace}" rsa
-			__generate_ssh_host_key "${replace}" dsa
-			;;
-		7)
-			__generate_ssh_host_key "${replace}" rsa1
-			__generate_ssh_host_key "${replace}" rsa
-			__generate_ssh_host_key "${replace}" dsa
-			__generate_ssh_host_key "${replace}" ecdsa
-			__generate_ssh_host_key "${replace}" ed25519
-			;;
-		*)
-			printf -- \
-				'Unknown EL release %s - skipping.\n' \
-				"${version}"
-			;;
-	esac
+	while read -r ssh_key || [[ -n ${ssh_key} ]]
+	do
+		if [[ -n ${ssh_key} ]] \
+			&& [[ $(
+				__get_ssh_key_fingerprint "${ssh_key}"
+			) =~ ${invalid_key_pattern} ]]
+		then
+			return 1
+		fi
+	done <<< "${authorized_keys}"
+
+	return 0
+}
+
+function __is_valid_ssh_chroot_directory ()
+{
+	local -r chroot_directory="${1}"
+	local -r safe_directory='^(%h|\/(?!\/|bin|dev|etc|lib|lib64|lost+found|media|proc|root|sbin|srv|sys|tmp|usr).+)$'
+
+	if [[ -z ${chroot_directory} ]]
+	then
+		return 1
+	fi
+
+	if grep -qoP "${safe_directory}" <<< "${chroot_directory}"
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_inherit_environment ()
+{
+	local -r boolean_value='^(true|false)$'
+	local -r value="${1}"
+
+	if [[ ${value} =~ ${boolean_value} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_key ()
+{
+	local -r public_key="${1}"
+	local -r invalid_key_pattern='is not a public key file.$'
+
+	if [[ -z ${public_key} ]]
+	then
+		return 1
+	fi
+
+	if [[ -n ${public_key} ]] \
+		&& [[ $(
+			__get_ssh_key_fingerprint "${public_key}"
+		) =~ ${invalid_key_pattern} ]]
+	then
+		return 1
+	fi
+
+	return 0
+}
+
+function __is_valid_ssh_password_authentication ()
+{
+	local -r boolean_value='^(true|false)$'
+	local -r value="${1}"
+
+	if [[ ${value} =~ ${boolean_value} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_sudo ()
+{
+	local -r temp_path="$(
+		mktemp -u
+	)"
+	local -r sudo_cmd="${1}"
+
+	if [[ -z ${sudo_cmd} ]]
+	then
+		return 1
+	fi
+
+	trap "rm -f \"${temp_path}\"" \
+		RETURN
+
+	printf -- \
+		'%%wheel %s\n' \
+		"${sudo_cmd}" \
+		> "${temp_path}"
+
+	if visudo \
+		-c \
+		-q \
+		-f "${temp_path}" \
+		&> /dev/null
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_timezone ()
+{
+	local -r zone="${1}"
+
+	if [[ -z ${zone} ]]
+	then
+		return 1
+	fi
+
+	if [[ -f /usr/share/zoneinfo/${zone} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_user ()
+{
+	local -r safe_user='^[a-z_][a-z0-9_-]{0,29}[$a-z0-9_]?$'
+	local -r user="${1}"
+
+	if [[ ${user} =~ ${safe_user} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_user_force_sftp ()
+{
+	local -r boolean_value='^(true|false)$'
+	local -r value="${1}"
+
+	if [[ ${value} =~ ${boolean_value} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_user_home ()
+{
+	local -r home_directory="${1}"
+	local -r user_directory='^\/(?!\/|bin|dev|etc|lib|lib64|lost+found|media|proc|root|sbin|srv|sys|tmp|usr).+$'
+	local -r root_directory='^/root$'
+	local -r user="${2:-"$(
+		__get_ssh_user
+	)"}"
+
+	local safe_directory="${user_directory}"
+
+	if [[ -z ${home_directory} ]]
+	then
+		return 1
+	fi
+
+	if [[ ${user} == root ]]
+	then
+		safe_directory="${root_directory}"
+	fi
+
+	if grep -qoP "${safe_directory}" <<< "${home_directory}"
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_user_id ()
+{
+	local -r id="${1}"
+	local -r user_id_pattern='^[1-9][0-9]*:[1-9][0-9]*$'
+	local -r root_id_pattern='^0:0$'
+	local -r user="${2:-"$(
+		__get_ssh_user
+	)"}"
+
+	local id_pattern="${user_id_pattern}"
+
+	if [[ ${user} == root ]]
+	then
+		id_pattern="${root_id_pattern}"
+	fi
+
+	if [[ ${id} =~ ${id_pattern} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_user_password_hash ()
+{
+	local -r password_hash="${1}"
+	local -r sha_512_pattern='^\$6\$[a-zA-Z0-9./]{0,16}\$[a-zA-Z0-9./]{86}$'
+
+	if [[ ${password_hash} =~ ${sha_512_pattern} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_user_password_hashed ()
+{
+	local -r boolean_value='^(true|false)$'
+	local -r value="${1}"
+
+	if [[ ${value} =~ ${boolean_value} ]]
+	then
+		return 0
+	fi
+
+	return 1
+}
+
+function __is_valid_ssh_user_shell ()
+{
+	local -r shell="${1}"
+	local -r valid_shells="$(
+		chsh --list-shells
+	)"
+
+	local valid_shell
+
+	if [[ -z ${shell} ]]
+	then
+		return 1
+	fi
+
+	for valid_shell in ${valid_shells}
+	do
+		if [[ ${valid_shell} == "${shell}" ]]
+		then
+			return 0
+		fi
+	done
+
+	return 1
 }
 
 function __set_ssh_timezone ()
@@ -940,8 +1002,9 @@ function main ()
 {
 	local -r env_exclude_pattern="^([.]*SSH_USER_PASSWORD|_|HOME|HOSTNAME|PATH|PWD|SHLVL|SUPERVISOR_ENABLED|SUPERVISOR_GROUP_NAME|SUPERVISOR_PROCESS_NAME|TERM)="
 	local -r lock_file="/var/lock/subsys/sshd-bootstrap"
-	local -r password_length=16
+	local -r password_length="16"
 	local -r redacted_value="********"
+	local -r state_file="/var/lib/misc/sshd-bootstrap"
 	local -r timer_start="$(
 		date +%s.%N
 	)"
@@ -985,20 +1048,39 @@ function main ()
 	local sshd_command="SSH"
 	local timer_total
 
-	# Create lock
-	touch \
-		"${lock_file}"
-
 	# Parse options
 	while [[ "${#}" -gt 0 ]]
 	do
 		case "${1}" in
 			-v|--verbose)
-				verbose=true
+				verbose="true"
 				shift 1
 				;;
 		esac
 	done
+
+	if [[ -e ${state_file} ]]
+	then
+		if [[ ${verbose} == true ]]
+		then
+			printf -- \
+				'INFO: %s finished - skipping.\n' \
+				"${0##*/}"
+		fi
+		exit 0
+	fi
+
+	if [[ -e ${lock_file} ]]
+	then
+		>&2 printf -- \
+			'ERROR: %s lock detected - aborting.\n' \
+			"${0##*/}"
+		exit 1
+	fi
+
+	trap "__cleanup" \
+		EXIT INT TERM
+	__create_lock
 
 	ssh_user_home="$(
 		__get_ssh_user_home
@@ -1092,11 +1174,8 @@ function main ()
 
 		if ! __set_ssh_timezone "${ssh_timezone}"
 		then
-			printf -- \
-				'ERROR: Could not set timezone - aborting.\n' \
-				>&2
-			sleep 0.1
-
+			>&2 printf -- \
+				'ERROR: Could not set timezone - aborting.\n'
 			exit 1
 		fi
 
@@ -1149,11 +1228,8 @@ function main ()
 
 		if ! __set_ssh_user_password "${ssh_user_password}"
 		then
-			printf -- \
-				'ERROR: Could not set password - aborting.\n' \
-				>&2
-			sleep 0.1
-
+			>&2 printf -- \
+				'ERROR: Could not set password - aborting.\n'
 			exit 1
 		fi
 
@@ -1371,14 +1447,8 @@ function main ()
 		if [[ ${verbose} == true ]]
 		then
 			timer_total="$(
-				awk \
-					-v timer_end="$(
-						date +%s.%N
-					)" \
-					-v timer_start="${timer_start}" \
-					'BEGIN { print \
-						timer_end - timer_start;
-					}'
+				__get_timer_total \
+					"${timer_start}"
 			)"
 
 			cat <<-EOT
@@ -1420,9 +1490,8 @@ function main ()
 		fi
 	fi
 
-	# Release lock
-	rm -f \
-		"${lock_file}"
+	# Trigger cleanup trap.
+	exit 0
 }
 
 main "${@}"
